name: Upload Report Artifact

on:
  workflow_dispatch:

jobs:
  upload-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip report.zip
        run: |
          mkdir -p report
          unzip -o report.zip -d report

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report/
