name: Upload and Publish Report

on:
  workflow_dispatch:

jobs:
  upload-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip report.zip
        run: |
          mkdir -p report
          unzip -o report.zip -d report

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: report

  deploy:
    needs: upload-report
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Add report link to summary
        run: echo "[📊 View Test Report](${{ steps.deployment.outputs.page_url }}/log.html)" >> $GITHUB_STEP_SUMMARY
